language: d

before_install:
    - sudo pip install --upgrade six
    - sudo pip install autobahntestsuite

script:
    - wstest -m fuzzingclient
    - dub test -b unittest-cov

after_success:
    - bash <(curl -s https://codecov.io/bash)
